export enum QueryKey {
  // Auth
  AUTH_USER = 'AUTH_USER',

  // Projects
  PROJECTS = 'PROJECTS',
  PROJECT = 'PROJECT',

  // Endpoints
  ENDPOINTS = 'ENDPOINTS',
  ENDPOINT = 'ENDPOINT',

  // Team
  TEAM_MEMBERS = 'TEAM_MEMBERS',
  TEAM_INVITES = 'TEAM_INVITES',
  MY_MEMBERSHIPS = 'MY_MEMBERSHIPS',

  // Versions
  VERSIONS = 'VERSIONS',
  VERSION = 'VERSION',

  // Notifications
  PENDING_INVITES = 'PENDING_INVITES',

  // Request logs
  REQUEST_LOGS = 'REQUEST_LOGS',

  // Scenarios
  SCENARIOS = 'SCENARIOS',
  SCENARIO = 'SCENARIO',

  // Scenario rules
  RULES = 'RULES',

  // Workspace
  MY_COMPANIES = 'MY_COMPANIES',
  COMPANY = 'COMPANY',
  PROFILE = 'PROFILE',
  MY_PROFILE = 'MY_PROFILE',
  PROFILES_IN_COMPANY = 'PROFILES_IN_COMPANY',
}
