export enum QueryKey {
  // Auth
  AUTH_USER = 'AUTH_USER',

  // Projects
  PROJECTS = 'PROJECTS',
  PROJECT = 'PROJECT',

  // Endpoints
  ENDPOINTS = 'ENDPOINTS',
  ENDPOINT = 'ENDPOINT',

  // Team
  TEAM_MEMBERS = 'TEAM_MEMBERS',
  TEAM_INVITES = 'TEAM_INVITES',
  MY_MEMBERSHIPS = 'MY_MEMBERSHIPS',

  // Versions
  VERSIONS = 'VERSIONS',
  VERSION = 'VERSION',

  // Notifications
  PENDING_INVITES = 'PENDING_INVITES',
}
