/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CompanySchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'id', 'logoUrl', 'name', 'ownerUserId', 'slug', 'updatedAt', 'visibility'] as const
  $columns = CompanySchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare logoUrl: string | null
  @column()
  declare name: string
  @column()
  declare ownerUserId: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare visibility: string
}

export class CompanyMetadatumSchema extends BaseModel {
  static $columns = ['billingAddress', 'billingEmail', 'companyId', 'createdAt', 'description', 'industry', 'settings', 'sizeBucket', 'totalMember', 'totalTeam', 'updatedAt', 'website'] as const
  $columns = CompanyMetadatumSchema.$columns
  @column()
  declare billingAddress: any | null
  @column()
  declare billingEmail: string | null
  @column({ isPrimary: true })
  declare companyId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare industry: string | null
  @column()
  declare settings: any
  @column()
  declare sizeBucket: string | null
  @column()
  declare totalMember: number
  @column()
  declare totalTeam: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare website: string | null
}

export class EndpointScenarioSchema extends BaseModel {
  static $columns = ['createdAt', 'delayMaxMs', 'delayMs', 'description', 'endpointId', 'id', 'isActive', 'name', 'priority', 'responseBody', 'responseHeaders', 'statusCode', 'updatedAt'] as const
  $columns = EndpointScenarioSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare delayMaxMs: number | null
  @column()
  declare delayMs: number | null
  @column()
  declare description: string | null
  @column()
  declare endpointId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare priority: number
  @column()
  declare responseBody: any | null
  @column()
  declare responseHeaders: any | null
  @column()
  declare statusCode: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EndpointSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'delayMaxMs', 'delayMs', 'id', 'isActive', 'method', 'path', 'projectId', 'responseBody', 'responseHeaders', 'statusCode', 'updatedAt'] as const
  $columns = EndpointSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column()
  declare delayMaxMs: number | null
  @column()
  declare delayMs: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean | null
  @column()
  declare method: string
  @column()
  declare path: string
  @column()
  declare projectId: string
  @column()
  declare responseBody: any | null
  @column()
  declare responseHeaders: any | null
  @column()
  declare statusCode: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProfileMetadatumSchema extends BaseModel {
  static $columns = ['bio', 'createdAt', 'department', 'jobTitle', 'lastActiveAt', 'links', 'phone', 'preferences', 'profileId', 'updatedAt'] as const
  $columns = ProfileMetadatumSchema.$columns
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare department: string | null
  @column()
  declare jobTitle: string | null
  @column.dateTime()
  declare lastActiveAt: DateTime | null
  @column()
  declare links: any
  @column()
  declare phone: string | null
  @column()
  declare preferences: any
  @column({ isPrimary: true })
  declare profileId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProfileSchema extends BaseModel {
  static $columns = ['avatarUrl', 'companyId', 'createdAt', 'displayName', 'id', 'joinedAt', 'leftAt', 'role', 'status', 'updatedAt', 'userId', 'visibility'] as const
  $columns = ProfileSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column()
  declare companyId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayName: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare joinedAt: DateTime | null
  @column.dateTime()
  declare leftAt: DateTime | null
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
  @column()
  declare visibility: string
}

export class ProjectInviteSchema extends BaseModel {
  static $columns = ['acceptedAt', 'createdAt', 'email', 'id', 'invitedBy', 'projectId', 'role', 'token', 'updatedAt'] as const
  $columns = ProjectInviteSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare invitedBy: string | null
  @column()
  declare projectId: string
  @column()
  declare role: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProjectSchema extends BaseModel {
  static $columns = ['basePath', 'createdAt', 'id', 'isPublic', 'name', 'ownerId', 'settings', 'slug', 'updatedAt'] as const
  $columns = ProjectSchema.$columns
  @column()
  declare basePath: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isPublic: boolean | null
  @column()
  declare name: string
  @column()
  declare ownerId: string
  @column()
  declare settings: any | null
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RequestLogSchema extends BaseModel {
  static $columns = ['createdAt', 'duration', 'endpointId', 'id', 'method', 'path', 'projectId', 'statusCode'] as const
  $columns = RequestLogSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare duration: number
  @column()
  declare endpointId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare method: string
  @column()
  declare path: string
  @column()
  declare projectId: string
  @column()
  declare statusCode: number
}

export class ScenarioRuleSchema extends BaseModel {
  static $columns = ['createdAt', 'field', 'id', 'operator', 'scenarioId', 'source', 'value'] as const
  $columns = ScenarioRuleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare field: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare operator: string
  @column()
  declare scenarioId: string
  @column()
  declare source: string
  @column()
  declare value: string | null
}

export class TeamMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'invitedAt', 'projectId', 'role', 'updatedAt', 'userId'] as const
  $columns = TeamMemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare invitedAt: DateTime
  @column()
  declare projectId: string
  @column()
  declare role: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class TeamMembershipSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'joinedAt', 'profileId', 'role', 'teamId', 'updatedAt'] as const
  $columns = TeamMembershipSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare joinedAt: DateTime
  @column()
  declare profileId: string
  @column()
  declare role: string
  @column()
  declare teamId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TeamMetadatumSchema extends BaseModel {
  static $columns = ['avatarUrl', 'color', 'createdAt', 'externalLinks', 'settings', 'teamId', 'totalMember', 'updatedAt'] as const
  $columns = TeamMetadatumSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalLinks: any
  @column()
  declare settings: any
  @column({ isPrimary: true })
  declare teamId: string
  @column()
  declare totalMember: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TeamSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'createdByProfileId', 'description', 'id', 'name', 'slug', 'updatedAt', 'visibility'] as const
  $columns = TeamSchema.$columns
  @column()
  declare companyId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByProfileId: string | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare visibility: string
}

export class UserTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'token', 'type', 'userId'] as const
  $columns = UserTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare token: string
  @column()
  declare type: string
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'email', 'emailVerified', 'id', 'name', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare emailVerified: boolean | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class VersionHistorySchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'id', 'message', 'projectId', 'snapshot'] as const
  $columns = VersionHistorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare message: string | null
  @column()
  declare projectId: string
  @column()
  declare snapshot: any
}
